# Generated by Django 3.0.3 on 2020-07-08 19:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('business', models.CharField(help_text='Бизнес-блок', max_length=3, primary_key=True, serialize=False, verbose_name='Бизнес-блок')),
                ('business_limit_forward', models.FloatField(help_text='Сумма лимита переходящего', verbose_name='Сумма лимита переходящего')),
                ('business_limit_week1', models.FloatField(help_text='Сумма лимита неделя 1', verbose_name='Сумма лимита неделя 1')),
                ('business_limit_week2', models.FloatField(help_text='Сумма лимита неделя 2', verbose_name='Сумма лимита неделя 2')),
                ('business_limit_week3', models.FloatField(help_text='Сумма лимита неделя 3', verbose_name='Сумма лимита неделя 3')),
                ('business_limit_week4', models.FloatField(help_text='Сумма лимита неделя 4', verbose_name='Сумма лимита неделя 4')),
                ('business_limit_week5', models.FloatField(help_text='Сумма лимита неделя 5', verbose_name='Сумма лимита неделя 5')),
            ],
            options={
                'ordering': ['business'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('sap_entity_code', models.CharField(help_text='SAP номер предприятия', max_length=4)),
                ('sap_vendor_code', models.CharField(help_text='SAP номер поставщика', max_length=10)),
                ('i_vendor_code', models.CharField(help_text='ЕДРПОУ', max_length=10)),
                ('i_vendor_name', models.CharField(help_text='Наименование поставщика', max_length=40)),
                ('sap_document_code', models.CharField(blank=True, help_text='Номер SAP документа', max_length=10)),
                ('sap_document_year', models.CharField(blank=True, help_text='Год SAP документа', max_length=4)),
                ('vendor_contract_number', models.CharField(help_text='Номер договора поставщика', max_length=20)),
                ('doc_date', models.DateField(blank=True, default='1001-01-01', help_text='Дата накладной')),
                ('doc_amount', models.FloatField(blank=True, help_text='Сумма накладной в валюте документа')),
                ('doc_currency', models.CharField(help_text='Валюта документа', max_length=3)),
                ('doc_duedate', models.DateField(help_text='Дата оплаты по договору')),
                ('vendor_document_code', models.CharField(help_text='Номер накладной поставщика', max_length=20)),
                ('doc_payment_block', models.CharField(blank=True, help_text='Блокировка платежа', max_length=1)),
            ],
            options={
                'ordering': ['vendor_contract_number'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('sap_vendor_code', models.CharField(help_text='SAP номер поставщика', max_length=10, primary_key=True, serialize=False, verbose_name='SAP номер поставщика')),
                ('vendor_edrpou', models.CharField(help_text='Балансовая единица', max_length=10, verbose_name='Балансовая единица')),
                ('vendor_name', models.CharField(help_text='Наименование поставщика', max_length=30, verbose_name='Наименование поставщика')),
                ('bank_limit', models.FloatField(help_text='Сумма лимита факторинга банка', verbose_name='Сумма лимита факторинга банка')),
                ('red_zone', models.BooleanField(default=False, help_text='Красная зона', verbose_name='Красная зона')),
            ],
            options={
                'ordering': ['vendor_edrpou'],
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('sap_entity_code', models.CharField(help_text='Балансовая единица', max_length=4, primary_key=True, serialize=False, verbose_name='Балансовая единица')),
                ('entity_name', models.CharField(help_text='Наименования предприятия', max_length=20, verbose_name='Наименования предприятия')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.Business')),
            ],
            options={
                'ordering': ['business', 'sap_entity_code'],
            },
        ),
        migrations.CreateModel(
            name='BKLimit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID', primary_key=True, serialize=False)),
                ('comment', models.CharField(help_text='Комментарий', max_length=30, verbose_name='Комментарий')),
                ('bk_limit_forward', models.FloatField(help_text='Сумма лимита переходящего', verbose_name='Сумма лимита переходящего')),
                ('bk_limit_week1', models.FloatField(help_text='Сумма лимита неделя 1', verbose_name='Сумма лимита неделя 1')),
                ('bk_limit_week2', models.FloatField(help_text='Сумма лимита неделя 2', verbose_name='Сумма лимита неделя 2')),
                ('bk_limit_week3', models.FloatField(help_text='Сумма лимита неделя 3', verbose_name='Сумма лимита неделя 3')),
                ('bk_limit_week4', models.FloatField(help_text='Сумма лимита неделя 4', verbose_name='Сумма лимита неделя 4')),
                ('bk_limit_week5', models.FloatField(help_text='Сумма лимита неделя 5', verbose_name='Сумма лимита неделя 5')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.Business')),
                ('sap_vendor_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cabinet.Vendor')),
            ],
            options={
                'ordering': ['business', 'sap_vendor_code'],
            },
        ),
    ]
