# Generated by Django 3.0.3 on 2020-07-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='doc_date',
            field=models.DateField(help_text='Дата накладной'),
        ),
    ]
