# Generated by Django 3.0.3 on 2020-07-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_auto_20200708_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='doc_amount',
            field=models.FloatField(help_text='Сумма накладной в валюте документа', null=True),
        ),
    ]
