# Generated by Django 3.0.3 on 2020-07-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_auto_20200708_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='doc_date',
            field=models.DateField(help_text='Дата накладной', null=True),
        ),
    ]
