# Generated by Django 3.0.3 on 2020-07-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_auto_20200708_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['i_vendor_code']},
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_edrpou',
            field=models.CharField(help_text='ЕДРПОУ', max_length=10, verbose_name='ЕДРПОУ'),
        ),
    ]
